/**
 * Cron job endpoint for scheduled post creation
 * Can be triggered by:
 * - Vercel Cron Jobs (if deployed on Vercel)
 * - External cron services (cron-job.org, EasyCron, etc.)
 * - GitHub Actions
 *
 * Usage:
 * GET /api/cron/create-post?secret=your-cron-secret
 */

import { NextRequest, NextResponse } from 'next/server';
import { markdownToPortableText } from '@/lib/markdown-to-portable-text';

// Force dynamic rendering for Vercel
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

/**
 * Generates blog post content using AI with research and synthesis
 * Replicates n8n workflow: research → synthesize → create unique insights
 * Supports OpenAI, Anthropic Claude, or other AI services
 */
async function generatePostContent(topic?: string): Promise<{
  markdown: string;
  title: string;
  excerpt: string;
  categoryIds?: string[];
  tagIds?: string[];
}> {
  const apiKey = process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    throw new Error('No AI API key found. Set OPENAI_API_KEY or ANTHROPIC_API_KEY');
  }

  // Enhanced system prompt for research-based content
  const systemPrompt = `You are an expert tech blogger who writes insightful, well-researched articles. You:
1. Synthesize information from multiple credible sources
2. Make connections between seemingly unrelated points
3. Create unique perspectives and insights
4. Write in an engaging, thought-provoking style
5. Structure content with clear headings, lists, and examples

Your articles are known for:
- Deep analysis and synthesis
- Unique insights that readers won't find elsewhere
- Connecting dots across different domains
- Actionable takeaways`;

  // Research and synthesis prompt
  const researchPrompt = topic
    ? `Research the topic: "${topic}".

Imagine you're pulling from credible sources (tech news sites, research papers, industry reports, Reddit discussions, HackerNews, etc.).

Extract:
1. 5-7 key points from these sources
2. 3-5 interesting connections or patterns
3. 2-3 unique insights or perspectives that most people miss
4. Counter-intuitive findings or contrarian viewpoints

Then synthesize this research into a comprehensive blog post.`
    : `Research current tech trends and news.

Imagine you're pulling from credible sources (tech news sites, research papers, industry reports, Reddit discussions, HackerNews, etc.).

Extract:
1. 5-7 key points from these sources
2. 3-5 interesting connections or patterns
3. 2-3 unique insights or perspectives that most people miss
4. Counter-intuitive findings or contrarian viewpoints

Then synthesize this research into a comprehensive blog post.`;

  const userPrompt = `${researchPrompt}

Create a blog post that:
1. Synthesizes the research into a coherent narrative
2. Highlights the most interesting connections
3. Develops unique insights further
4. Tells a compelling story

Format as markdown with:
- A clear, engaging title (as H1)
- An excerpt/summary paragraph (2-3 sentences)
- Well-structured sections with headings (H2, H3)
- Bullet points and examples where appropriate
- **Bold text** for emphasis
- *Italic text* for subtle emphasis
- Links where relevant (use [text](url) format)
- Code blocks if discussing technical concepts

Make it insightful, unique, and valuable. Length should be substantial (1500-3000 words equivalent).`;

  // Option 1: Use OpenAI
  if (process.env.OPENAI_API_KEY) {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL || 'gpt-4',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.7,
        max_tokens: 4000,
      }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: { message: response.statusText } }));
      throw new Error(`OpenAI API error: ${error.error?.message || response.statusText}`);
    }

    const data = await response.json();
    const aiContent = data.choices[0].message.content;

    if (!aiContent) {
      throw new Error('AI did not return any content.');
    }

    // Extract title and excerpt
    const titleMatch = aiContent.match(/^#\s+(.+?)$/m);
    const title = titleMatch ? titleMatch[1].trim() : (topic || 'AI Generated Post');

    // Extract excerpt (first paragraph after title, or first 2-3 sentences)
    const contentAfterTitle = aiContent.replace(/^#\s+.+?\n\n?/m, '');
    const excerptMatch = contentAfterTitle.match(/^(.+?)(?:\n\n|$)/m);
    const excerpt = excerptMatch
      ? excerptMatch[1].trim().substring(0, 200) + (excerptMatch[1].length > 200 ? '...' : '')
      : 'A new post generated by AI.';

    return {
      markdown: aiContent,
      title,
      excerpt,
      categoryIds: [],
      tagIds: [],
    };
  }

  // Option 2: Use Anthropic Claude
  if (process.env.ANTHROPIC_API_KEY) {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL || 'claude-3-sonnet-20240229',
        max_tokens: 2000,
        messages: [
          {
            role: 'user',
            content: 'Write a blog post about latest tech trends in Markdown format. Include a title (H1), excerpt, and well-structured content.',
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Anthropic API error: ${response.statusText}`);
    }

    const data = await response.json();
    const markdown = data.content[0].text;

    // Extract title and excerpt
    const titleMatch = markdown.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1] : 'Untitled Post';
    const excerptMatch = markdown.match(/\n\n([^\n]+)/);
    const excerpt = excerptMatch ? excerptMatch[1].substring(0, 150) : '';

    return { markdown, title, excerpt };
  }

  // Fallback: Return error if no AI service configured
  throw new Error('No AI service configured. Set OPENAI_API_KEY or ANTHROPIC_API_KEY in environment variables.');
}

export async function GET(request: NextRequest) {
  try {
    // Verify cron secret
    const secret = request.nextUrl.searchParams.get('secret');
    const expectedSecret = process.env.CRON_SECRET;

    if (expectedSecret && secret !== expectedSecret) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Get optional topic parameter
    const topic = request.nextUrl.searchParams.get('topic') || undefined;

    // Generate post content with research and synthesis
    const { markdown, title, excerpt, categoryIds, tagIds } = await generatePostContent(topic);

    // Import via internal API call (reuses your existing logic)
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || request.nextUrl.origin;
    const importResponse = await fetch(`${baseUrl}/api/import-markdown`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        // Include API key if set
        ...(process.env.API_KEY && { 'x-api-key': process.env.API_KEY }),
      },
      body: JSON.stringify({
        markdown,
        title,
        excerpt,
        categoryIds,
        tagIds,
      }),
    });

    if (!importResponse.ok) {
      const error = await importResponse.json();
      throw new Error(error.error || 'Failed to import post');
    }

    const result = await importResponse.json();

    return NextResponse.json({
      success: true,
      message: 'Post created successfully',
      post: result.post,
    });
  } catch (error) {
    console.error('Error in cron job:', error);
    return NextResponse.json(
      {
        error: 'Failed to create post',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// Also support POST for external cron services
export async function POST(request: NextRequest) {
  return GET(request);
}

